title: FreshKeep UH
description: UHM ICS 414 Project FALL 2025
header_pages:
  - index.md
  - team-contact.md
  - user-guide.md
  - dev-guide.md
style: light # dark (default)
footer: 'latest updates'
remote_theme: "jekyll/minima@c6e74bb"
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
minima:
  hide_site_feed_link: true
  social_links:
    - title: FreshKeepuh repository at GitHub
      icon: github
      url: "https://github.com/freshkeepuh/freshkeep"